### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by arichiardi** [kovrik/cider-diet#1]
I know I know it is super early to say anything about this :smile: but I wanted to report this. My steps:
- `git clone ...`
- `lein install`
- include `[cider-diet/cider-diet "0.1.0-SNAPSHOT" :scope "test"]` in my boot dependencies
- launch `boot with-cp -w` (generates the classpath)
- launch `drip -cp src:$(cat cp) cider_diet.core`

The last part is in a shell script and I can easily connect and work with cider after that.
The boot time is fast but you need to remember to generate the classpath when you change deps (I can live with it, actually a `boot` script can be created that launches the `with-cp` command only when the deps changed from "the last time").

I cannot test with the `echo (System/exit 0) | java -cp ...` trick because `cider_diet.core/-main` does not handle it but it feels it is around 6 seconds here, which is very very good.

A suggestion would be to make it a namespace without `-` so that you avoid confusion (like `clojure.main`) but again these things can be all settled in cider directly maybe.

For now I will use this with jubilation :smile:

**Comment by kovrik** [comment]
@arichiardi 
Thank you for your response (and for testing)!

> I cannot test with the echo (System/exit 0) | java -cp ... trick because cider_diet.core/-main does not handle it but it

Yes, true.
I just wanted to make it as simple as possible.
All evaluation is supposed to happen from Emacs inside CIDER session afterwards.

> A suggestion would be to make it a namespace without - so that you avoid confusion (like clojure.main) but again these things can be all settled in cider directly maybe.

Can you please elaborate this?
Are you suggesting to get rid of dash char `-` in the name?

Overall, the sole purpose of this 'project' was to demonstrate that we can get working nREPL (with middleware) much faster than current `cider-jack-in` gives us.
Which does **not** mean that we should replace `cider-jack-in` with this toy project.
But that **does** mean that we should investigate on why it takes so long to run nREPL via `cider-jack-in` (and `lein repl`).

Meanwhile, yes, feel free to use this as a temporary solution until cider/lein gets fixed :)

**Comment by arichiardi** [comment]
@kovrik I created a boot task, for now not very generic but working fine:
https://gist.github.com/arichiardi/86ccc450e243e9964e723d73f2f1db2c

**Comment by arichiardi** [comment]
Ah I did not answer to your question, yes it is just a super minor problem, but because you've choose a namespace with `-` people have to remember to convert it to `_`. So if you drop that basically you improve the affordance of your lib :smile: My suggestion would be `cider.diet` where `diet.clj` contains the main, but ok, enough philosophy for now.

**Comment by kovrik** [comment]
@arichiardi 
Andrea, thank you for that!
That is not a problem, I'll definitely change namespace name per your suggestion.

**Comment by kovrik** [comment]
@arichiardi 
See my latest commit.
Renamed namespace to `cider.diet` (144bc436d8f945147c982252c0dc2ec51db5934c)

Can you please have a look and check if it is better now?
Are there any other changes you'd like to see to make integration easier?

**Comment by arichiardi** [comment]
Looks, perfect thanks! Are you going to release a `0.1.1`?
For now I guess it is enough! I discovered that my task has a flaw in that the inner process does not see environment variable, but this is not really a `cider-diet` concern :wink:

**Comment by kovrik** [comment]
> Are you going to release a 0.1.1?

Don't know yet :)
If I find some time for improving things.

Currently I have 2 concerns:
1) Don't know if all dependencies are required
2) I am not sure that it handles SIGINT (Ctrl-C) and other signals properly

Anyway, thank you very much for your help! Really appreciate it!

**Comment by arichiardi** [comment]
No problem! My pleasure. About 2, I found: http://stackoverflow.com/a/2541950, so it looks like it is included in the package, am I right?

**Comment by kovrik** [comment]
@arichiardi 
Well, yeah, I don't think there is a problem with signal handling.
Just not sure that `cider-diet`'s interacion with `nrepl` server 100% correct.
But, anyway, it is working fine, so I guess it is ok to leave it as it is for now.

**Comment by arichiardi** [comment]
@kovrik asking for a release (or at least a push of `SNAPSHOT` on Clojars) because another potential user would like to try it out, but you know sometimes devs are lazy and don't like to `git clone` `lein install` :smile:

EDIT: ok I talking about myself as well lol

**Comment by kovrik** [comment]
@arichiardi 
https://clojars.org/cider-diet
:smile: 

Can you check it please?

PS: But how are you going to use it via clojars?

**Comment by arichiardi** [comment]
Awesome!

I updated the task, which is now very generic (see `cider-diet` not the one below), it could be even included in this project :smile: https://gist.github.com/arichiardi/86ccc450e243e9964e723d73f2f1db2c

About your question, using this task and `micha.boot-cp/with-cp` I generate the classpath and dump it in a file, downloading  it from clojars.

It works smoothly thanks!

```
Retrieving maven-metadata.xml from https://clojars.org/repo/ (1k)
Retrieving cider-diet-0.1.0-20160706.232151-1.pom from https://clojars.org/repo/
Retrieving cider-diet-0.1.0-20160706.232151-1.jar from https://clojars.org/repo/ (3852k)
```

**Comment by kovrik** [comment]
@arichiardi 
Oh, I see!
Cool :smile: 

Let me know if you encounter any issues/come up with any improvements

**Comment by DrakoAI** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!jumpdest7d, @0xBadMad, @zhangzone, @0x00214131812049, @dok852, @0xicingdeath, @tanliwei, @y3zha, @NatawatK, @GoodHut, @AliErcanOzgokce, @HiT0on, @debris, @spilehchiha, @tseitz, @fakeorf3ke, @iFrostizz, @thefrisson, @mklodt, @juliusjulyp
